FROM node:18-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages/
COPY ./package-lock.json ./package-lock.json

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/websocket ./apps/websocket

RUN npm install
RUN npm run db:generate

EXPOSE 8081

CMD ["npm", "run", "start:websocket"]