FROM node:20-alpine
WORKDIR /usr/src/app
COPY ./packages ./packages
COPY ./package-lock.json ./package-lock.json
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/fe ./apps/fe
RUN npm install
RUN npm run build
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "apps/fe/dist", "-l", "3000"]